### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by JimRou** [gaelm/afis-moulinette#3]
Depuis la dernière évolution, ça ne marche plus chez moi. Le fichier texte est vide. Voici les messages d'erreur que j'ai (je suis sous python3.7) :

```
sudo python ./afis-moulinette.py SPS_325-P_48-50.epub 
CSS template: OEBPS/template.css
article: OEBPS/Sans titre-2.xhtml -> ./SPS_325-P_48-50.Sans titre-2.txt
Traceback (most recent call last):
  File "./afis-moulinette.py", line 300, in <module>
    epub2spip(args.FILE, args.output_dir)
  File "./afis-moulinette.py", line 273, in epub2spip
    wh.write(xhtml2spip(xhtml, css))
  File "./afis-moulinette.py", line 239, in xhtml2spip
    root = etree.XML(content, parser)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 85, column 181
```

**Comment by gaelm** [comment]
C'était du à l'ampersand & dans des urls, j'ai remplacé les & par les entités XML &amp;
C'est corrigé.
